### ISSUE TITLE
username set

### ISSUE THREAD

**Issue by boyfromhell** [grohman/OctoSocialite#3]
Hello.
Thanks for the plugin,
I was able to do thanks to login with social networks.

But a question.
How can I do to let users to set up a Username.
I mean to not generate random one.

Thanks in advance.

**Comment by grohman** [comment]
Usernames are provided by RainLab.User. Get current user through the relation with users-table and do whatever you need.

**Comment by boyfromhell** [comment]
Sorry, my bad.
I wanted to say when the user is registered,
it does not exist in the database.

**Comment by grohman** [comment]
If there is no user, than create one. For example, you can catch user-token afterCreate event (https://octobercms.com/docs/database/model#events) and retrieve user-data from remote service (name, photo, etc). Than you need to create user with this data.

**Comment by boyfromhell** [comment]
Now 
`composer require socialiteproviders/instagram`

`Driver [instagram] not supported.`
